Repository dong-greemy/dg-client, pull requests merged in 2024-10, with the labels that each got.

#6 스타일 세팅 및 헤더 퍼블리싱
  public/assets/icon512_maskable.png
  public/assets/icon512_rounded.png
  public/assets/svg/back-icon.svg
  public/assets/svg/close-icon.svg
  public/assets/svg/logo.svg
  public/sw.js.map
  src/app/layout.tsx
  src/app/manifest.json
  src/app/page.tsx
  src/app/providers.tsx
  src/app/styles.ts
  src/components/header/index.tsx
  src/components/header/styles.ts
  src/lib/registry.tsx
  src/styles/color.ts
  src/styles/common.ts
  src/styles/global.ts
  src/styles/media.ts
  src/styles/theme.ts
  src/styles/typography.ts
  tsconfig.json
  yarn.lock
Labels: chore, feat, style

#9 폴더 구조 수정 및 홈 퍼블리싱
  public/images/icon512_maskable.png
  public/images/icon512_rounded.png
  public/svg/back-icon.svg
  public/svg/close-icon.svg
  public/svg/logo.svg
  public/svg/search-icon.svg
  public/sw.js.map
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles.ts
  src/components/AboutService/index.tsx
  src/components/AboutService/styled.ts
  src/components/Button/index.tsx
  src/components/Button/styled.ts
  src/components/header/index.tsx
  src/components/header/styled.ts
  src/containers/home/index.tsx
  src/containers/home/styled.ts
  src/libs/registry.tsx
  src/styles/common.ts
  tsconfig.json
Labels: feat, refactor

#10 next-pwa 관련 파일 gitignore 설정
  .gitignore
  public/sw.js.map
Labels: chore

#12 랜딩 페이지 제작
  public/svg/ios-share.svg
  src/app/landing/page.tsx
  src/components/Button/index.tsx
  src/components/Button/styled.ts
  src/components/header/index.tsx
  src/components/header/styled.ts
  src/components/landing/Graphic/index.tsx
  src/components/landing/Graphic/styled.ts
  src/components/landing/Text/index.tsx
  src/components/landing/Text/styled.ts
  src/containers/landing/index.tsx
  src/containers/landing/styled.ts
  src/styles/common.ts
Labels: feat, fix
